<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4NDnA65\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4NDnA65/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4NDnA65.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4NDnA65\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container4NDnA65\srcDevDebugProjectContainer(array(
    'container.build_hash' => '4NDnA65',
    'container.build_id' => '0b0a3544',
    'container.build_time' => 1532454920,
), __DIR__.\DIRECTORY_SEPARATOR.'Container4NDnA65');
