<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container02vvYR4\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container02vvYR4/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container02vvYR4.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container02vvYR4\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container02vvYR4\srcDevDebugProjectContainer(array(
    'container.build_hash' => '02vvYR4',
    'container.build_id' => 'fe22cfbf',
    'container.build_time' => 1532512909,
), __DIR__.\DIRECTORY_SEPARATOR.'Container02vvYR4');
